# -*- coding: utf-8 -*-
"""Milestone3 (Ai Lab).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPfpkrcJGFbTYsj7o0sd77AORU8YkJk1
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import shutil

# ==============================
# Configuration
# ==============================

# Original dataset
SOURCE_DATASET = "/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset"

# New 20% dataset
DEST_DATASET = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent"

# Percentage to keep
PERCENTAGE = 0.20

# Reproducibility
random.seed(42)

IMAGE_EXTENSIONS = (
    ".jpg", ".jpeg", ".png",
    ".bmp", ".tif", ".tiff"
)

# ==============================
# Copy Dataset
# ==============================

splits = ["train", "val", "test"]

# Create destination directories
os.makedirs(DEST_DATASET, exist_ok=True)

for split in splits:

    split_path = os.path.join(SOURCE_DATASET, split)

    # Skip if split doesn't exist
    if not os.path.exists(split_path):
        print(f"⚠️ Split '{split}' not found at {split_path} - skipping")
        continue

    # Get all classes in this split
    try:
        classes = sorted(os.listdir(split_path))
    except NotADirectoryError:
        print(f"⚠️ {split_path} is not a directory - skipping")
        continue

    for cls in classes:

        class_path = os.path.join(split_path, cls)

        if not os.path.isdir(class_path):
            continue

        # Get all images
        try:
            images = [
                img for img in os.listdir(class_path)
                if img.lower().endswith(IMAGE_EXTENSIONS)
            ]
        except FileNotFoundError:
            print(f"⚠️ Class path not found: {class_path} - skipping")
            continue

        total_images = len(images)

        # Skip empty directories
        if total_images == 0:
            print(f"{split}/{cls}")
            print(f"⚠️ No images found - skipping")
            print("-"*40)
            continue

        # Calculate sample size (minimum 1)
        sample_size = max(1, int(total_images * PERCENTAGE))

        # Sample images
        sampled_images = random.sample(images, sample_size)

        # Create destination folder
        destination_folder = os.path.join(
            DEST_DATASET,
            split,
            cls
        )

        os.makedirs(destination_folder, exist_ok=True)

        # Copy images with error handling
        success_count = 0
        for image in sampled_images:

            src = os.path.join(class_path, image)
            dst = os.path.join(destination_folder, image)

            try:
                shutil.copy2(src, dst)
                success_count += 1
            except FileNotFoundError:
                print(f"⚠️ File not found: {src} - skipping")
            except Exception as e:
                print(f"⚠️ Error copying {src}: {e} - skipping")

        print(f"{split}/{cls}")
        print(f"Original : {total_images}")
        print(f"Copied   : {success_count} / {sample_size}")
        print("-"*40)

# ==============================
# Summary
# ==============================
print("\n" + "="*50)
print("DATASET CREATION SUMMARY")
print("="*50)

# Count files in destination
total_files = 0
for root, dirs, files in os.walk(DEST_DATASET):
    for file in files:
        if file.lower().endswith(IMAGE_EXTENSIONS):
            total_files += 1

print(f"\n✅ Total images copied: {total_files}")
print(f"✅ Destination: {DEST_DATASET}")

# Show per-split statistics
for split in splits:
    split_path = os.path.join(DEST_DATASET, split)
    if os.path.exists(split_path):
        count = 0
        for root, dirs, files in os.walk(split_path):
            for file in files:
                if file.lower().endswith(IMAGE_EXTENSIONS):
                    count += 1
        print(f"   {split}: {count} images")

print("\n✅ 20% candidate dataset created successfully!")

pip install torch torchvision scikit-learn tqdm pandas matplotlib

import torch
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import pandas as pd

# -----------------------
# Configuration
# -----------------------

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

BATCH_SIZE = 32

VAL_DIR = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent/val"

NUM_CLASSES = 5

# -----------------------
# Validation Transform
# -----------------------

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=transform
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print(val_dataset.classes)

def evaluate_model(model):

    model.eval()

    preds = []
    labels = []

    with torch.no_grad():

        for images, target in tqdm(val_loader):

            images = images.to(DEVICE)
            target = target.to(DEVICE)

            outputs = model(images)

            prediction = outputs.argmax(1)

            preds.extend(prediction.cpu().numpy())
            labels.extend(target.cpu().numpy())

    acc = accuracy_score(labels, preds)

    precision = precision_score(
        labels,
        preds,
        average='weighted',
        zero_division=0
    )

    recall = recall_score(
        labels,
        preds,
        average='weighted'
    )

    f1 = f1_score(
        labels,
        preds,
        average='weighted'
    )

    return acc, precision, recall, f1

"""**MobileNetV3**"""

weights = torchvision.models.MobileNet_V3_Large_Weights.DEFAULT

model = torchvision.models.mobilenet_v3_large(weights=weights)

model.classifier[3] = torch.nn.Linear(
    model.classifier[3].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

mobile_results = evaluate_model(model)

"""**ResNet50**"""

weights = torchvision.models.ResNet50_Weights.DEFAULT

model = torchvision.models.resnet50(weights=weights)

model.fc = torch.nn.Linear(
    model.fc.in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

resnet_results = evaluate_model(model)

"""**EfficientNet-B0**"""

weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT

model = torchvision.models.efficientnet_b0(weights=weights)

model.classifier[1] = torch.nn.Linear(
    model.classifier[1].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

efficient_results = evaluate_model(model)

comparison = pd.DataFrame({

    "Model":[
        "MobileNetV3",
        "ResNet50",
        "EfficientNet-B0"
    ],

    "Accuracy":[
        mobile_results[0],
        resnet_results[0],
        efficient_results[0]
    ],

    "Precision":[
        mobile_results[1],
        resnet_results[1],
        efficient_results[1]
    ],

    "Recall":[
        mobile_results[2],
        resnet_results[2],
        efficient_results[2]
    ],

    "F1 Score":[
        mobile_results[3],
        resnet_results[3],
        efficient_results[3]
    ]
})

print(comparison)

comparison.to_csv("baseline_comparison.csv", index=False)

import copy
import time
import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support

import pandas as pd
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

train_dir = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent/train"
val_dir = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent/val"

transform_train = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
])

transform_val = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

train_dataset = datasets.ImageFolder(train_dir, transform_train)
val_dataset = datasets.ImageFolder(val_dir, transform_val)

train_loader = DataLoader(train_dataset,
                          batch_size=32,
                          shuffle=True)

val_loader = DataLoader(val_dataset,
                        batch_size=32,
                        shuffle=False)

num_classes = len(train_dataset.classes)

print(train_dataset.classes)

def get_model(name):

    if name=="MobileNetV3":

        model = models.mobilenet_v3_large(weights="DEFAULT")
        in_features = model.classifier[3].in_features
        model.classifier[3] = nn.Linear(in_features,num_classes)

    elif name=="ResNet50":

        model = models.resnet50(weights="DEFAULT")
        in_features = model.fc.in_features
        model.fc = nn.Linear(in_features,num_classes)

    elif name=="EfficientNetB0":

        model = models.efficientnet_b0(weights="DEFAULT")
        in_features = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_features,num_classes)

    return model.to(device)

def train_one_model(model):

    criterion = nn.CrossEntropyLoss()

    optimizer = optim.AdamW(model.parameters(),lr=0.001)

    epochs = 10

    model.train()

    for epoch in range(epochs):

        running_loss=0

        for images,labels in tqdm(train_loader):

            images=images.to(device)
            labels=labels.to(device)

            optimizer.zero_grad()

            outputs=model(images)

            loss=criterion(outputs,labels)

            loss.backward()

            optimizer.step()

            running_loss+=loss.item()

        print(f"Epoch {epoch+1} Loss={running_loss/len(train_loader):.4f}")

def evaluate(model):

    model.eval()

    preds=[]
    labels_list=[]

    with torch.no_grad():

        for images,labels in val_loader:

            images=images.to(device)

            outputs=model(images)

            pred=torch.argmax(outputs,1)

            preds.extend(pred.cpu().numpy())

            labels_list.extend(labels.numpy())

    accuracy=accuracy_score(labels_list,preds)

    precision,recall,f1,_=precision_recall_fscore_support(
        labels_list,
        preds,
        average="weighted"
    )

    return accuracy,precision,recall,f1

model_names = [
    "MobileNetV3",
    "ResNet50",
    "EfficientNetB0"
]

results=[]

for name in model_names:

    print("="*60)
    print(name)

    model=get_model(name)

    train_one_model(model)

    acc,pre,rec,f1=evaluate(model)

    results.append([name,acc,pre,rec,f1])

df=pd.DataFrame(results,
columns=[
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score"
])

print(df)

import matplotlib.pyplot as plt
import pandas as pd

data = {
"Experiment":["Baseline","LR=0.0005","LR=0.0001","BS=16","BS=64","SGD","AdamW"],
"Accuracy":[93.98,91.67,93.98,91.20,95.83,39.35,90.27]
}

df=pd.DataFrame(data)

plt.figure(figsize=(8,5))
plt.plot(df["Experiment"],df["Accuracy"],marker='o')
plt.xticks(rotation=30)
plt.ylabel("Accuracy (%)")
plt.title("Hyperparameter Comparison")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# ----------------------------------------------------
# Hyperparameter Experiment Results (Best model of each experiment)
# ----------------------------------------------------
data = {
    "Experiment": [
        "Baseline\nAdam\nLR=0.001\nBS=32",
        "LR=0.0005",
        "LR=0.0001",
        "BS=16",
        "BS=64",
        "SGD",
        "AdamW"
    ],

    "Accuracy": [
        93.98,
        91.67,
        93.98,
        91.20,
        95.83,
        39.35,
        90.28
    ],

    "Precision": [
        94.08,
        91.91,
        94.11,
        91.57,
        95.89,
        43.36,
        90.43
    ],

    "Recall": [
        93.98,
        91.67,
        93.98,
        91.20,
        95.83,
        39.35,
        90.28
    ],

    "F1 Score": [
        93.98,
        91.68,
        94.02,
        91.22,
        95.81,
        35.90,
        90.10
    ]
}

df = pd.DataFrame(data)

# ----------------------------------------------------
# Plot Function
# ----------------------------------------------------
def plot_metric(metric):
    plt.figure(figsize=(9,5))

    plt.plot(
        df["Experiment"],
        df[metric],
        marker='o',
        linewidth=2,
        markersize=8
    )

    plt.title(f"{metric} Comparison Across Hyperparameter Experiments",
              fontsize=14)

    plt.ylabel(metric + " (%)")
    plt.xlabel("Experiments")

    plt.xticks(rotation=20)

    plt.grid(True)

    # Display values above points
    for x, y in zip(df["Experiment"], df[metric]):
        plt.text(x, y+0.5, f"{y:.2f}",
                 ha='center',
                 fontsize=9)

    plt.tight_layout()
    plt.show()


# ----------------------------------------------------
# Generate all plots
# ----------------------------------------------------
plot_metric("Accuracy")
plot_metric("Precision")
plot_metric("Recall")
plot_metric("F1 Score")

import matplotlib.pyplot as plt
import numpy as np

models = ["MobileNetV3", "ResNet50", "EfficientNet-B0"]

accuracy = [89.35, 92.13, 93.98]
precision = [89.74, 92.32, 94.08]
recall = [89.35, 92.13, 93.98]
f1 = [89.39, 92.14, 93.98]

x = np.arange(len(models))
width = 0.2

plt.figure(figsize=(10,6))

plt.bar(x-width*1.5, accuracy, width, label='Accuracy')
plt.bar(x-width/2, precision, width, label='Precision')
plt.bar(x+width/2, recall, width, label='Recall')
plt.bar(x+width*1.5, f1, width, label='F1 Score')

plt.xticks(x, models, fontsize=12)
plt.ylabel("Percentage (%)", fontsize=12)
plt.ylim(0,100)
plt.title("Performance Comparison of Candidate Models")
plt.legend()

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=300)
plt.show()

import matplotlib.pyplot as plt

experiments = [
    "Baseline",
    "LR=0.0005",
    "LR=0.0001",
    "BS=16",
    "BS=64",
    "SGD",
    "AdamW"
]

accuracy = [87.04,90.74,87.96,87.96,68.06,42.13,89.81]

plt.figure(figsize=(10,5))

plt.plot(experiments, accuracy, marker='o', linewidth=2)

for i,v in enumerate(accuracy):
    plt.text(i,v+0.6,str(v),ha='center')

plt.ylabel("Accuracy (%)")
plt.xlabel("Experiment")
plt.title("MobileNetV3 Hyperparameter Comparison")
plt.grid(True)

plt.tight_layout()
plt.savefig("hyperparameter_comparison.png",dpi=300)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

metrics = ["Accuracy","Precision","Recall","F1"]

data = np.array([
    [89.35,89.74,89.35,89.39],
    [92.13,92.32,92.13,92.14],
    [93.98,94.08,93.98,93.98]
])

models = ["MobileNetV3","ResNet50","EfficientNet-B0"]

fig, ax = plt.subplots(figsize=(7,4))

im = ax.imshow(data)

ax.set_xticks(np.arange(len(metrics)))
ax.set_yticks(np.arange(len(models)))

ax.set_xticklabels(metrics)
ax.set_yticklabels(models)

plt.title("Performance Heatmap")

for i in range(len(models)):
    for j in range(len(metrics)):
        ax.text(j, i, f"{data[i,j]:.2f}",
                ha="center", va="center", color="black")

plt.colorbar(im)

plt.tight_layout()
plt.savefig("performance_heatmap.png",dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

experiments = [
    "Baseline",
    "LR=5e-4",
    "LR=1e-4",
    "BS16",
    "BS64",
    "SGD",
    "AdamW"
]

accuracy = np.array([[87.04,90.74,87.96,87.96,68.06,42.13,89.81]])

fig, ax = plt.subplots(figsize=(10,2.5))
im = ax.imshow(accuracy)

ax.set_xticks(np.arange(len(experiments)))
ax.set_xticklabels(experiments, rotation=45)

ax.set_yticks([0])
ax.set_yticklabels(["Accuracy"])

for i in range(accuracy.shape[0]):
    for j in range(accuracy.shape[1]):
        ax.text(j, i, f"{accuracy[i,j]:.2f}",
                ha="center", va="center")

plt.colorbar(im)

plt.title("Hyperparameter Experiment Heatmap")

plt.tight_layout()
plt.show()

import torch
import torchvision.models as models

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None),
    "ResNet50": models.resnet50(weights=None),
    "EfficientNet-B0": models.efficientnet_b0(weights=None)
}

for name, model in models_dict.items():
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)

    print(f"{name}")
    print(f"Total Parameters: {total:,}")
    print(f"Trainable Parameters: {trainable:,}")
    print("-"*40)

pip install ptflops

from ptflops import get_model_complexity_info
import torchvision.models as models

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None),
    "ResNet50": models.resnet50(weights=None),
    "EfficientNet-B0": models.efficientnet_b0(weights=None)
}

for name, model in models_dict.items():

    macs, params = get_model_complexity_info(
        model,
        (3,224,224),
        as_strings=True,
        print_per_layer_stat=False,
        verbose=False
    )

    print(name)
    print("FLOPs (MACs):", macs)
    print("Parameters:", params)
    print()

import torch
import torchvision.models as models

device = torch.device("cuda")

dummy = torch.randn(1,3,224,224).to(device)

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None).to(device),
    "ResNet50": models.resnet50(weights=None).to(device),
    "EfficientNet-B0": models.efficientnet_b0(weights=None).to(device)
}

for name, model in models_dict.items():

    torch.cuda.empty_cache()

    torch.cuda.reset_peak_memory_stats()

    with torch.no_grad():
        model(dummy)

    mem = torch.cuda.max_memory_allocated()/1024**2

    print(name, mem,"MB")

import torch
import time
import torchvision.models as models

device = torch.device("cuda")

dummy = torch.randn(1,3,224,224).to(device)

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None).to(device),
    "ResNet50": models.resnet50(weights=None).to(device),
    "EfficientNet-B0": models.efficientnet_b0(weights=None).to(device)
}

for name, model in models_dict.items():

    model.eval()

    # warmup
    for _ in range(20):
        model(dummy)

    torch.cuda.synchronize()

    start = time.time()

    for _ in range(200):
        model(dummy)

    torch.cuda.synchronize()

    end = time.time()

    latency = (end-start)/200*1000

    fps = 1000/latency

    print(name)
    print("Latency:",latency,"ms")
    print("FPS:",fps)
    print()