# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hilBdFhsqfjn801jku1PYqUiz-6nun3t
"""

# ============================================
# MobileNetV3 Driver Activity Classification
# Complete Inference Pipeline
# ============================================

import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
import numpy as np
import os
import time
import json
from typing import Union, List, Dict, Any, Optional
from dataclasses import dataclass, asdict
import warnings
warnings.filterwarnings('ignore')


# ============================================
# 1. Configuration
# ============================================
@dataclass
class InferenceConfig:
    """Configuration for inference pipeline."""

    # Model parameters
    input_size: int = 224
    num_classes: int = 5
    class_names: List[str] = None

    # Device settings
    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'

    # Inference settings
    use_amp: bool = False  # Mixed precision
    batch_size: int = 1

    # Thresholds
    confidence_threshold: float = 0.5

    def __post_init__(self):
        if self.class_names is None:
            self.class_names = [
                'other_activities',
                'safe_driving',
                'talking_phone',
                'texting_phone',
                'turning'
            ]


# ============================================
# 2. Prediction Result
# ============================================
@dataclass
class PredictionResult:
    """Prediction result structure."""

    module: str = "Driver Activity Classification"
    prediction: str = ""
    confidence: float = 0.0
    risk_score: float = 0.0
    metadata: Dict[str, Any] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'module': self.module,
            'prediction': self.prediction,
            'confidence': self.confidence,
            'risk_score': self.risk_score,
            'metadata': self.metadata
        }


# ============================================
# 3. Preprocessor
# ============================================
class ImagePreprocessor:
    """Image preprocessing pipeline."""

    def __init__(self, config: InferenceConfig):
        self.config = config
        self.transform = self._build_transform()

    def _build_transform(self) -> transforms.Compose:
        """Build preprocessing transform pipeline."""
        return transforms.Compose([
            transforms.Resize((self.config.input_size, self.config.input_size)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]
            )
        ])

    def preprocess(self, image: Union[str, np.ndarray, Image.Image]) -> torch.Tensor:
        """
        Preprocess input image.

        Args:
            image: Image path, numpy array, or PIL Image

        Returns:
            Preprocessed tensor (1, 3, 224, 224)
        """
        # Load image if path is provided
        if isinstance(image, str):
            if not os.path.exists(image):
                raise FileNotFoundError(f"Image not found: {image}")
            pil_image = Image.open(image).convert('RGB')
        elif isinstance(image, np.ndarray):
            # Convert numpy array to PIL Image
            if image.ndim == 3:
                pil_image = Image.fromarray(image)
            else:
                raise ValueError(f"Invalid image shape: {image.shape}")
        elif isinstance(image, Image.Image):
            pil_image = image.convert('RGB')
        else:
            raise TypeError(f"Unsupported image type: {type(image)}")

        # Apply transforms
        tensor = self.transform(pil_image)

        # Add batch dimension
        return tensor.unsqueeze(0)  # (1, 3, 224, 224)


# ============================================
# 4. Model Loader
# ============================================
class ModelLoader:
    """Model loading and management."""

    @staticmethod
    def load_model(
        checkpoint_path: str,
        config: InferenceConfig
    ) -> nn.Module:
        """
        Load trained model from checkpoint.

        Args:
            checkpoint_path: Path to checkpoint file
            config: Inference configuration

        Returns:
            Loaded model in eval mode
        """
        if not os.path.exists(checkpoint_path):
            raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

        # Create model architecture
        model = models.mobilenet_v3_large(weights=None)
        model.classifier[3] = nn.Linear(
            in_features=1280,
            out_features=config.num_classes
        )

        # Load checkpoint
        checkpoint = torch.load(checkpoint_path, map_location=config.device)

        # Extract model state dict
        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
            print(f"✅ Loaded model from epoch {checkpoint.get('epoch', 'N/A')}")
            print(f"   Best Validation Accuracy: {checkpoint.get('best_val_acc', 'N/A')}%")

            # Update class names if available
            if 'class_names' in checkpoint:
                config.class_names = checkpoint['class_names']
        else:
            model.load_state_dict(checkpoint)
            print("✅ Loaded model (direct state dict)")

        # Set to eval mode
        model = model.to(config.device)
        model.eval()

        return model


# ============================================
# 5. Risk Calculator
# ============================================
class RiskCalculator:
    """Risk score calculation."""

    # Risk mapping for each class
    RISK_MAPPING = {
        'safe_driving': 0.05,
        'turning': 0.20,
        'talking_phone': 0.60,
        'other_activities': 0.70,
        'texting_phone': 0.85
    }

    @classmethod
    def calculate_risk(cls, predicted_class: str, confidence: float) -> float:
        """
        Calculate risk score based on prediction and confidence.

        Args:
            predicted_class: Predicted class name
            confidence: Confidence score (0-100)

        Returns:
            Risk score (0-1)
        """
        base_risk = cls.RISK_MAPPING.get(predicted_class, 0.50)
        confidence_factor = confidence / 100.0
        return base_risk * confidence_factor


# ============================================
# 6. Main Predictor
# ============================================
class DriverActivityPredictor:
    """
    Driver Activity Classification Inference Pipeline.

    This class handles the complete inference pipeline:
    1. Image preprocessing
    2. Model inference
    3. Postprocessing
    4. Risk calculation
    """

    def __init__(
        self,
        checkpoint_path: str,
        config: Optional[InferenceConfig] = None,
        lazy_load: bool = False
    ):
        """
        Initialize the predictor.

        Args:
            checkpoint_path: Path to model checkpoint
            config: Inference configuration (optional)
            lazy_load: If True, load model on first prediction
        """
        self.checkpoint_path = checkpoint_path
        self.config = config or InferenceConfig()
        self._model = None
        self._preprocessor = None
        self._lazy_load = lazy_load

        # Initialize preprocessor
        self._preprocessor = ImagePreprocessor(self.config)

        # Load model immediately if not lazy loading
        if not lazy_load:
            self._load_model()

        print(f"✅ Predictor initialized on {self.config.device}")
        print(f"   Classes: {self.config.class_names}")

    def _load_model(self):
        """Load the model."""
        if self._model is None:
            self._model = ModelLoader.load_model(
                self.checkpoint_path,
                self.config
            )

    def _ensure_model_loaded(self):
        """Ensure model is loaded (for lazy loading)."""
        if self._model is None:
            self._load_model()

    def warmup(self) -> None:
        """
        Warmup the model by running dummy inference.
        This initializes CUDA kernels and allocates memory.
        """
        self._ensure_model_loaded()

        dummy_input = torch.randn(1, 3, 224, 224).to(self.config.device)

        with torch.no_grad():
            _ = self._model(dummy_input)

        # Clear cache
        if self.config.device == 'cuda':
            torch.cuda.empty_cache()

        print("✅ Model warmup complete")

    def unload(self) -> None:
        """
        Unload the model and release resources.
        """
        if self._model is not None:
            # Move to CPU before deletion
            self._model = self._model.to('cpu')
            del self._model
            self._model = None

            # Clear GPU cache
            if self.config.device == 'cuda':
                torch.cuda.empty_cache()

            print("✅ Model unloaded")

    def predict(
        self,
        image: Union[str, np.ndarray, Image.Image]
    ) -> Dict[str, Any]:
        """
        Predict driver activity from a single image.

        Args:
            image: Image path, numpy array (RGB), or PIL Image

        Returns:
            Prediction result dictionary
        """
        start_time = time.time()

        # Ensure model is loaded
        self._ensure_model_loaded()

        # Preprocess image
        input_tensor = self._preprocessor.preprocess(image)
        input_tensor = input_tensor.to(self.config.device)

        # Inference
        with torch.no_grad():
            if self.config.use_amp and self.config.device == 'cuda':
                with torch.cuda.amp.autocast():
                    outputs = self._model(input_tensor)
            else:
                outputs = self._model(input_tensor)

            probabilities = torch.softmax(outputs, dim=1)
            confidence, predicted = torch.max(probabilities, 1)

        # Get results
        predicted_index = predicted.item()
        predicted_class = self.config.class_names[predicted_index]
        confidence_score = confidence.item() * 100

        # Calculate risk score
        risk_score = RiskCalculator.calculate_risk(predicted_class, confidence_score)

        # Create metadata
        metadata = {
            'predicted_index': predicted_index,
            'probabilities': {
                self.config.class_names[i]: float(probabilities[0][i].item())
                for i in range(len(self.config.class_names))
            },
            'inference_time_ms': (time.time() - start_time) * 1000,
            'model_version': 'v1.0.0',
            'timestamp': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
            'device': self.config.device,
            'input_shape': input_tensor.shape
        }

        # Return result
        return {
            'module': 'Driver Activity Classification',
            'prediction': predicted_class,
            'confidence': confidence_score,
            'risk_score': risk_score,
            'metadata': metadata
        }

    def predict_batch(
        self,
        images: List[Union[str, np.ndarray, Image.Image]]
    ) -> List[Dict[str, Any]]:
        """
        Predict driver activity for multiple images.

        Args:
            images: List of images

        Returns:
            List of prediction result dictionaries
        """
        results = []
        for image in images:
            result = self.predict(image)
            results.append(result)
        return results

    def predict_video(
        self,
        video_path: str,
        output_path: Optional[str] = None,
        frame_skip: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Process video and generate predictions.

        Args:
            video_path: Path to video file
            output_path: Optional path to save annotated video
            frame_skip: Process every Nth frame

        Returns:
            List of predictions per processed frame
        """
        try:
            import cv2
        except ImportError:
            raise ImportError("OpenCV (cv2) is required for video processing")

        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Video not found: {video_path}")

        cap = cv2.VideoCapture(video_path)
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        print(f"📹 Processing video: {fps}fps, {width}x{height}, {total_frames} frames")

        predictions = []
        frame_count = 0
        processed_count = 0

        out = None
        if output_path:
            fourcc = cv2.VideoWriter_fourcc(*'mp4v')
            out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            if frame_count % frame_skip == 0:
                # Convert BGR to RGB
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                # Predict
                result = self.predict(frame_rgb)
                result['metadata']['frame_number'] = frame_count
                predictions.append(result)
                processed_count += 1

                # Draw prediction on frame
                if output_path:
                    pred = result['prediction']
                    conf = result['confidence']

                    # Color based on risk
                    risk = result['risk_score']
                    if risk > 0.7:
                        color = (0, 0, 255)  # Red - High risk
                    elif risk > 0.4:
                        color = (0, 255, 255)  # Yellow - Medium risk
                    else:
                        color = (0, 255, 0)  # Green - Low risk

                    cv2.putText(
                        frame,
                        f"{pred}: {conf:.1f}%",
                        (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.8,
                        color,
                        2,
                        cv2.LINE_AA
                    )
                    out.write(frame)

            frame_count += 1

        cap.release()
        if out:
            out.release()

        print(f"✅ Processed {processed_count} frames")
        return predictions


# ============================================
# 7. Module Adapter (For Module Manager Integration)
# ============================================
class DriverActivityAdapter:
    """
    Adapter for integration with the Driver Wellness Module Manager.
    """

    def __init__(
        self,
        model_path: str,
        device: Optional[str] = None
    ):
        """
        Initialize the adapter.

        Args:
            model_path: Path to model checkpoint
            device: Device to run inference on
        """
        self.config = InferenceConfig(device=device or InferenceConfig.device)
        self.predictor = DriverActivityPredictor(
            model_path,
            config=self.config,
            lazy_load=True
        )

    def warmup(self) -> None:
        """Warmup the model."""
        self.predictor.warmup()

    def unload(self) -> None:
        """Unload the model."""
        self.predictor.unload()

    def predict(self, image: Union[str, np.ndarray, Image.Image]) -> Dict[str, Any]:
        """
        Predict driver activity.

        Args:
            image: Input image

        Returns:
            Standard output contract dictionary
        """
        result = self.predictor.predict(image)

        # Ensure standard format
        return {
            'module': 'Driver Activity Classification',
            'prediction': result['prediction'],
            'confidence': result['confidence'],
            'risk_score': result['risk_score'],
            'metadata': result['metadata']
        }

    def predict_batch(self, images: List) -> List[Dict[str, Any]]:
        """Predict for multiple images."""
        return self.predictor.predict_batch(images)


# ============================================
# 8. Main Entry Point
# ============================================
if __name__ == "__main__":
    # Example usage

    # 1. Initialize predictor
    predictor = DriverActivityPredictor(
        checkpoint_path='./checkpoints/best_mobilenetv3.pth',
        config=InferenceConfig(device='cuda' if torch.cuda.is_available() else 'cpu')
    )

    # 2. Warmup
    predictor.warmup()

    # 3. Single image prediction
    print("\n" + "="*60)
    print("SINGLE IMAGE PREDICTION")
    print("="*60)

    # Replace with your image path
    test_image = '/path/to/test_image.jpg'

    if os.path.exists(test_image):
        result = predictor.predict(test_image)

        print(f"\n📊 Prediction Result:")
        print(f"   Module: {result['module']}")
        print(f"   Prediction: {result['prediction']}")
        print(f"   Confidence: {result['confidence']:.2f}%")
        print(f"   Risk Score: {result['risk_score']:.3f}")
        print(f"\n   Probabilities:")
        for cls, prob in result['metadata']['probabilities'].items():
            print(f"     {cls}: {prob*100:.2f}%")
        print(f"\n   Inference Time: {result['metadata']['inference_time_ms']:.2f}ms")

    # 4. Video processing (optional)
    # test_video = '/path/to/video.mp4'
    # if os.path.exists(test_video):
    #     predictions = predictor.predict_video(test_video, frame_skip=5)

    # 5. Unload model
    # predictor.unload()